### ISSUE TITLE
Install failing following instructions

### ISSUE THREAD

**Issue by ryanleesipes** [mivoq/fatts#3]
Similar to issue #2 - the following error occurs when running "mvn install" in the repo:

```

[ERROR]   The project de.dfki.mary:marytts:5.2-SNAPSHOT (/home/ryan.sipes/fatts/pom.xml) has 4 errors

[ERROR]     Child module /home/ryan.sipes/fatts/marytts-client of /home/ryan.sipes/fatts/pom.xml does not exist

[ERROR]     Child module /home/ryan.sipes/fatts/marytts-builder of /home/ryan.sipes/fatts/pom.xml does not exist

[ERROR]     Child module /home/ryan.sipes/fatts/marytts-redstart of /home/ryan.sipes/fatts/pom.xml does not exist

[ERROR]     Child module /home/ryan.sipes/fatts/marytts-transcription of /home/ryan.sipes/fatts/pom.xml does not exist
```

It's right, the modules don't seem to exist in the repo. Should they be removed, and upon doing so FATTS still fails to install. Thoughts? Advice

**Comment by giuliopaci** [comment]
As I mentioned in issue #2 these are sources for the debian packages. While fatts is opensource, its development has been conducted mostly without publishing and will need some work before we can make it public.

The right tools for compilation are thus gbp and/or dpkg-buildpackage.

If you want to manually compile these sources, first you have to apply the patches contained in debian/patches, then you can follow the standard instructions.
